// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymxmdhshkwrgyvpvwmmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlteG1kaHNoa3dyZ3l2cHZ3bW1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4ODQ3MTUsImV4cCI6MjA2ODQ2MDcxNX0.UyWasAnU67wDmc62426uM1uf3XZxNHbKQqThpijTHKA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});